modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "ore_deposits"
version = "${version}"
displayName = "Synth's Ore Deposits"
authors = "Me!"
description = '''
In-exhaustive ores!
'''
#logoFile = ""

[[dependencies.ore_deposits]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ore_deposits]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ore_deposits]]
modId = "architectury"
mandatory = true
versionRange = "[4.9.83,)"
ordering = "AFTER"
side = "BOTH"