modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "ore_deposits"
version = "${version}"
displayName = "Synth's Ore Deposits"
authors = "Daan Schar [Synthesyzer]"
description = '''
In-exhaustive ores!
'''
#logoFile = ""

[[dependencies.ore_deposits]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ore_deposits]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ore_deposits]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"